version: '3.9'

services:
  php:
    container_name: php-container
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80

  mysql:
    container_name: mysql-container
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  adminer:
    container_name: adminer-container
    image: adminer
    restart: always
    ports:
      - 9001:80
